version: '3.3'

services:
  backend:
    build: ./backend/
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_HOST=http://localhost
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "80:80"

